name: run twitter_scapper.py

on: push
  # schedule:
#     # - cron: '0 0 * * *' 
#     # - cron: '15 22 * * *' 

jobs:
  scrape-twitter:
    runs-on: ubuntu-latest

    container:
      image: python:3.9

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Configure git to trust the workspace despite the different owner
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global user.name "SreevaatsavB"
          git config --global user.email "bavanasreevaatsav1@gmail.com"
          
      - name: Scrape Twitter
        run: python twitter_scape.py
        shell: sh
#         run: python -u twitter_scape.py

  
      - name: commit
        run: |
          git add -A
          git commit -m "Automated commit: added scraped data"
          git push origin main --force

      # - name: commit files
      #   run: |
      #     git config --global user.name "SreevaatsavB"
      #     git config --global user.email "bavanasreevaatsav1@gmail.com"
      #     git add .
      #     git commit -m "Automated commit: added scraped data"
      #     git push
